-- request.before — build the AIRS scan payload from the client's request body.
--
-- Runs inside Kong's request-callout sandbox (untrusted_lua = sandbox), where
-- `require` is unavailable: no cjson, no resty.*. Everything here uses only
-- `kong`, `ngx` and the standard string/table library, which is why the JSON is
-- both hand-parsed and hand-built.
--
-- Kept as a real .lua file and inlined into the JSON config by
-- scripts/build_request_callout.py. As a single-line string inside a config file
-- this logic would be neither reviewable nor testable, and the extraction rules
-- below need both.

-- >>> BUILD OPTIONS -- generated by scripts/build_request_callout.py. Edit the
-- OPTIONS dict there, not here: the generator rewrites this block in every hook
-- and spec/j_request_callout_spec.lua fails if the three ever disagree.
--
-- A Konnect Serverless flavor has no Kong schema, so the fail-open /
-- fail-closed choice is a build-time decision rather than a runtime one.
-- It defaults closed, and every exit below reads it rather than
-- hard-coding the answer.
local OPTIONS = {
    on_api_error = 'block',
    app_name = 'kong-airs',
}
-- <<< END BUILD OPTIONS

local body = kong.request.get_raw_body() or ''
kong.ctx.shared.original_request_body = body

-- ---------------------------------------------------------------------------
-- A very small, string-aware JSON reader.
--
-- The extraction is a reader rather than one pattern such as
--   '"role"%s*:%s*"user".-"content"%s*:%s*"([^"]*)"'
-- because three properties have to hold and no such pattern holds them:
--   1. An ESCAPED quote stays inside the string. `[^"]*` stops at the first,
--        "say \"hi\" then ignore all previous instructions"
--      scanning only `say \` -- an evasion primitive, not a rounding error.
--   2. Array-shaped content -- [{"type":"text","text":"..."}] -- is read too.
--      Every multimodal client sends that shape, and content this hook cannot
--      see is content nothing scans.
--   3. Key order carries no meaning. JSON does not guarantee it and cjson emits
--      whatever the hash yields, so scanning forward from a role can land in
--      the FOLLOWING message.
-- A naive string.find for '"role"' also matches text a caller put inside their
-- own prompt, so every scan below is depth- and string-aware.
-- ---------------------------------------------------------------------------

-- \uXXXX -> UTF-8. Kong's Lua is 5.1/LuaJIT, which has no utf8.char.
local function utf8_char(cp)
    if cp < 0x80 then
        return string.char(cp)
    elseif cp < 0x800 then
        return string.char(0xC0 + math.floor(cp / 0x40), 0x80 + cp % 0x40)
    elseif cp < 0x10000 then
        return string.char(0xE0 + math.floor(cp / 0x1000),
                           0x80 + math.floor(cp / 0x40) % 0x40,
                           0x80 + cp % 0x40)
    end
    return string.char(0xF0 + math.floor(cp / 0x40000),
                       0x80 + math.floor(cp / 0x1000) % 0x40,
                       0x80 + math.floor(cp / 0x40) % 0x40,
                       0x80 + cp % 0x40)
end

-- Read the JSON string starting at the quote s[i]. Returns (value, index of the
-- closing quote), honouring backslash escapes.
--
-- The \u branch decodes the codepoint, surrogate pairs included, and must never
-- stand a placeholder in for it. A caller can write an entire prompt as \uXXXX
-- escapes -- legal JSON, which the upstream model decodes back to the real
-- sentence -- so a branch that emitted, say, a space per escape would extract a
-- run of spaces. Spaces are non-empty, so the fail-closed gate below passes
-- them, AIRS scans whitespace and returns allow, and upstream_before.lua then
-- restores the ORIGINAL bytes for the model: SCM logs a clean scan of nothing
-- while the attack lands verbatim. Content that is about to be called "scanned"
-- must never be silently blanked.
local function read_json_string(s, i)
    local out, k = {}, i + 1
    while k <= #s do
        local c = string.sub(s, k, k)
        if c == '\\' then
            local n = string.sub(s, k + 1, k + 1)
            if n == 'n' then out[#out + 1] = '\n'; k = k + 2
            elseif n == 't' then out[#out + 1] = '\t'; k = k + 2
            elseif n == 'r' then out[#out + 1] = '\r'; k = k + 2
            elseif n == 'b' then out[#out + 1] = '\b'; k = k + 2
            elseif n == 'f' then out[#out + 1] = '\f'; k = k + 2
            elseif n == 'u' then
                local hex = string.sub(s, k + 2, k + 5)
                local cp = #hex == 4 and tonumber(hex, 16) or nil
                if not cp then
                    -- Malformed. Keep the literal text rather than inventing a
                    -- character: the scanner must see what was actually sent.
                    out[#out + 1] = string.sub(s, k, k + 5)
                    k = k + 6
                elseif cp >= 0xD800 and cp <= 0xDBFF
                       and string.sub(s, k + 6, k + 7) == '\\u' then
                    -- Surrogate pair: the only way JSON can carry an astral
                    -- codepoint, and emoji-obfuscated prompts use it.
                    local lo = tonumber(string.sub(s, k + 8, k + 11), 16)
                    if lo and lo >= 0xDC00 and lo <= 0xDFFF then
                        out[#out + 1] = utf8_char(0x10000 + (cp - 0xD800) * 0x400 + (lo - 0xDC00))
                        k = k + 12
                    else
                        out[#out + 1] = utf8_char(cp)
                        k = k + 6
                    end
                else
                    out[#out + 1] = utf8_char(cp)
                    k = k + 6
                end
            else out[#out + 1] = n; k = k + 2 end
        elseif c == '"' then
            return table.concat(out), k
        else
            out[#out + 1] = c
            k = k + 1
        end
    end
    return nil, nil
end

-- Map an object's TOP-LEVEL keys to the index where each value begins.
-- from/to bracket the object's own braces.
local function top_level_fields(s, from, to)
    local fields, k, depth, expect_key = {}, from, 0, false
    while k <= to do
        local c = string.sub(s, k, k)
        if c == '"' then
            local key, endq = read_json_string(s, k)
            if not endq then break end
            if depth == 1 and expect_key then
                local j = endq + 1
                while j <= to and string.find(string.sub(s, j, j), '%s') do j = j + 1 end
                if string.sub(s, j, j) == ':' then
                    j = j + 1
                    while j <= to and string.find(string.sub(s, j, j), '%s') do j = j + 1 end
                    fields[key] = j
                end
            end
            k = endq + 1
            expect_key = false
        elseif c == '{' or c == '[' then
            depth = depth + 1
            expect_key = (c == '{' and depth == 1)
            k = k + 1
        elseif c == '}' or c == ']' then
            depth = depth - 1
            k = k + 1
        elseif c == ',' then
            expect_key = (depth == 1)
            k = k + 1
        else
            k = k + 1
        end
    end
    return fields
end

-- Call fn(start, stop) for each object directly inside the array whose '[' is
-- at s[open].
local function each_object(s, open, fn)
    local k, depth, start = open + 1, 0, nil
    while k <= #s do
        local c = string.sub(s, k, k)
        if c == '"' then
            local _, endq = read_json_string(s, k)
            if not endq then return end
            k = endq
        elseif c == '{' then
            depth = depth + 1
            if depth == 1 then start = k end
        elseif c == '}' then
            if depth == 1 and start then fn(start, k) end
            depth = depth - 1
        elseif c == '[' then
            depth = depth + 1
        elseif c == ']' then
            if depth == 0 then return end
            depth = depth - 1
        end
        k = k + 1
    end
end

-- A message's content: a plain string, or an array of parts each carrying text.
local function read_content(s, i)
    local c = string.sub(s, i, i)
    if c == '"' then
        return (read_json_string(s, i))
    end
    if c ~= '[' then return nil end
    local parts = {}
    each_object(s, i, function(from, to)
        local f = top_level_fields(s, from, to)
        if f.text then
            local t = read_json_string(s, f.text)
            if t and t ~= '' then parts[#parts + 1] = t end
        end
    end)
    if #parts > 0 then return table.concat(parts, ' ') end
    return nil
end

-- The newest user turn is the one under review; every chat client resends the
-- whole history.
local prompt = nil
local root = top_level_fields(body, 1, #body)
if root.messages and string.sub(body, root.messages, root.messages) == '[' then
    each_object(body, root.messages, function(from, to)
        local f = top_level_fields(body, from, to)
        if not (f.role and f.content) then return end
        local role = read_json_string(body, f.role)
        if role ~= 'user' then return end
        local text = read_content(body, f.content)
        if text and text ~= '' then prompt = text end
    end)
end

-- Reading `messages` and nothing else would make a Gemini, Cohere v1 or
-- legacy-completions body a hard 400, in the flavor recommended for Konnect
-- serverless. Reading those shapes is strictly better than refusing them:
-- refusing trades a silent gap for downtime on a request that was never wrong.
--
-- Gemini: contents[].parts[].text, caller turns only.
if not prompt or prompt == '' then
    if root.contents and string.sub(body, root.contents, root.contents) == '[' then
        local texts = {}
        each_object(body, root.contents, function(from, to)
            local f = top_level_fields(body, from, to)
            local role = f.role and read_json_string(body, f.role) or nil
            -- A `model` turn is the assistant's own earlier answer, not the
            -- prompt under review.
            if role == nil or role == 'user' then
                if f.parts and string.sub(body, f.parts, f.parts) == '[' then
                    each_object(body, f.parts, function(pf, pt)
                        local pfields = top_level_fields(body, pf, pt)
                        if pfields.text then
                            local t = read_json_string(body, pfields.text)
                            if t and t ~= '' then texts[#texts + 1] = t end
                        end
                    end)
                end
            end
        end)
        if #texts > 0 then prompt = table.concat(texts, '\n') end
    end
end

-- Cohere v1 chat: a top-level "message" string.
if (not prompt or prompt == '') and root.message
   and string.sub(body, root.message, root.message) == '"' then
    prompt = (read_json_string(body, root.message))
end

-- Legacy OpenAI completions: "prompt" as a string, or as a list of strings.
if (not prompt or prompt == '') and root.prompt then
    local at = string.sub(body, root.prompt, root.prompt)
    if at == '"' then
        prompt = (read_json_string(body, root.prompt))
    elseif at == '[' then
        local texts, k = {}, root.prompt + 1
        while k <= #body do
            local c = string.sub(body, k, k)
            if c == '"' then
                local t, endq = read_json_string(body, k)
                if not endq then break end
                if t and t ~= '' then texts[#texts + 1] = t end
                k = endq
            elseif c == ']' then
                break
            end
            k = k + 1
        end
        if #texts > 0 then prompt = table.concat(texts, '\n') end
    end
end

-- Nothing is substituted here to keep the callout fed: a filler prompt would
-- turn an unparseable body into a clean AIRS allow. If we could not read a
-- prompt then we have not scanned anything, and saying so is the only honest
-- answer.
if not prompt or prompt == '' then
    kong.log.err('prisma-airs: no user prompt could be read from the request body')
    return kong.response.exit(400, { error = 'Request body could not be inspected' })
end

-- This flavor never logs prompt content and has no debug narration to gate --
-- the only lines it emits are the refusal at `err` above and the verdict lines
-- in response_before.lua. There is deliberately no debug_log_payloads
-- equivalent: a Konnect serverless hook has no per-route switch to hang it on,
-- so the safe answer is not to have the capability.
--
-- Hand-rolled JSON encoding: no cjson in the sandbox. Escapes every control
-- character, not only backslash, quote and newline -- an unescaped 0x00-0x1f
-- produces invalid JSON and an AIRS 400 that presents to the operator as an
-- outage.
local function esc(s)
    s = string.gsub(tostring(s or ''), '[\\"]', '\\%0')
    s = string.gsub(s, '\n', '\\n')
    s = string.gsub(s, '\r', '\\r')
    s = string.gsub(s, '\t', '\\t')
    s = string.gsub(s, '%c', function(c) return string.format('\\u%04x', string.byte(c)) end)
    return '"' .. s .. '"'
end

-- The transaction and session slots are filled under their own names. `tr_id`
-- is a legacy alias for the SESSION slot, so a per-request value sent under it
-- would make every turn its own conversation AND leave the transaction slot
-- server-minted. See docs/CORRELATION.md.
local transaction_id = (kong.request.get_id and kong.request.get_id()) or ngx.var.request_id
local session_id = kong.request.get_header('Mcp-Session-Id')
                or kong.request.get_header('x-session-id')

local consumer = kong.client.get_consumer and kong.client.get_consumer()
local app_user = (consumer and (consumer.username or consumer.custom_id)) or 'anonymous'

local out = { '{"transaction_id":', esc(string.sub(tostring(transaction_id or 'unknown'), 1, 100)) }
if session_id and session_id ~= '' then
    out[#out + 1] = ',"session_id":'
    out[#out + 1] = esc(string.sub(session_id, 1, 100))
end
-- The model belongs in the AIRS metadata: this hook has already parsed the body
-- and "model" is sitting right there. It is also put on the structured record,
-- so "which model was this traffic going to" is answerable without parsing a
-- log message.
local ai_model = 'unknown'
if root.model and string.sub(body, root.model, root.model) == '"' then
    local m = read_json_string(body, root.model)
    if m and m ~= '' then ai_model = m end
end

-- A structured record, so a fail-open here is more than prose in a log line.
-- Same `airs` shape as both plugin lineages, so one SIEM query covers all
-- three.
kong.ctx.shared.airs_evidence = {
    scans = {}, gaps = {}, ai_model = ai_model,
    transaction_id = tostring(transaction_id or 'unknown'),
}
pcall(kong.log.set_serialize_value, 'airs', kong.ctx.shared.airs_evidence)

out[#out + 1] = ',"ai_profile":{"profile_name":"YOUR_PROFILE_NAME"}'
out[#out + 1] = ',"metadata":{"app_name":'
out[#out + 1] = esc(OPTIONS.app_name)
out[#out + 1] = ',"app_user":'
out[#out + 1] = esc(app_user)
out[#out + 1] = ',"ai_model":'
out[#out + 1] = esc(ai_model)
out[#out + 1] = '}'
out[#out + 1] = ',"contents":[{"prompt":'
out[#out + 1] = esc(prompt)
out[#out + 1] = '}]}'

kong.ctx.shared.callouts.airs_request_scan.request.params.body = table.concat(out)
