-- response.before — act on the AIRS verdict.
--
-- The callout's HTTP status is checked before its body is read, and a 200 has
-- to carry an explicit verdict before the request may continue. A bare
-- substring test,
--
--   if body:match('"action"%s*:%s*"block"') then ... exit 403 ... end
--
-- holds neither property: a bad API key returns 401, whose body contains no
-- such string, so the prompt would reach the model completely unscanned, the
-- client would get HTTP 200, and nothing anywhere would record that the
-- guardrail had not run -- the opposite of what the README promises. This is
-- the flavor recommended for Konnect serverless; keep both checks.

-- >>> BUILD OPTIONS -- generated by scripts/build_request_callout.py. Edit the
-- OPTIONS dict there, not here: the generator rewrites this block in every hook
-- and spec/j_request_callout_spec.lua fails if the three ever disagree.
--
-- A Konnect Serverless flavor has no Kong schema, so the fail-open /
-- fail-closed choice is a build-time decision rather than a runtime one.
-- It defaults closed, and every exit below reads it rather than
-- hard-coding the answer.
local OPTIONS = {
    on_api_error = 'block',
    app_name = 'kong-airs',
}
-- <<< END BUILD OPTIONS

local co = kong.ctx.shared.callouts
local scan = co and co.airs_request_scan
local res = scan and scan.response

-- A structured record, so a fail-open leaves more than prose behind. `airs`
-- matches the shape both plugin lineages emit.
local evidence = kong.ctx.shared.airs_evidence
if type(evidence) ~= 'table' then
    evidence = { scans = {}, gaps = {} }
    kong.ctx.shared.airs_evidence = evidence
end
local function publish()
    pcall(kong.log.set_serialize_value, 'airs', evidence)
end
local function record_gap(kind, detail)
    evidence.gaps[#evidence.gaps + 1] = { kind = kind, detail = detail }
    publish()
end
local function record_scan(action, category, scan_id, failed_open)
    evidence.scans[#evidence.scans + 1] = {
        leg = 'prompt', action = action,
        outcome = failed_open and 'failed_open'
                  or (action == 'error' and 'fail_closed' or 'verdict'),
        enforced = not failed_open,
        category = category, scan_id = scan_id,
    }
    publish()
end

-- This flavor has no Kong schema, so fail-open vs fail-closed is a build-time
-- option rather than a config field: `OPTIONS.on_api_error`, which the exits
-- below honour. It defaults to closed.
--
-- Log levels are split the way Kong's convention wants them: `notice` for the
-- guardrail doing its job, `err` for something the operator has to act on. A
-- policy block is not an operator problem; an unreachable scanner is.
local function scanner_unavailable(detail)
    kong.log.err('prisma-airs: ' .. detail)
    if OPTIONS.on_api_error == 'allow' then
        record_gap('api_error_allowed', detail)
        record_scan('error', nil, nil, true)
        return
    end
    record_scan('error', nil, nil)
    return kong.response.exit(503, { error = 'Security scanning unavailable' })
end

local function blocked(category, scan_id)
    kong.log.notice('prisma-airs: Blocking. Verdict: block' ..
                    (category and (', Category: ' .. tostring(category)) or ''))
    record_scan('block', category, scan_id)
    kong.ctx.shared.airs_blocked = true
    return kong.response.exit(403, { error = 'Blocked by AI security scan' })
end

-- No response object at all: the callout did not complete.
if not res then
    return scanner_unavailable('no scan response; failing closed')
end

if res.status ~= 200 then
    return scanner_unavailable('scan returned HTTP ' .. tostring(res.status) .. '; failing closed')
end

local body = res.body
if type(body) == 'table' then
    -- request-callout decoded it for us.
    if body.action ~= 'allow' then
        return blocked(body.category, body.scan_id)
    end
    record_scan('allow', nil, body.scan_id)
    return
end

body = body or ''
if string.match(body, '"action"%s*:%s*"block"') then
    return blocked(string.match(body, '"category"%s*:%s*"([^"]*)"'),
                   string.match(body, '"scan_id"%s*:%s*"([^"]*)"'))
end

-- A 200 whose body we cannot interpret is still not a verdict. Treating "no
-- block string" as "allowed" would be the same fail-open by a different route:
-- a captive portal or an intercepting proxy answering 200 with HTML would pass
-- every prompt straight through.
if not string.match(body, '"action"%s*:%s*"allow"') then
    return scanner_unavailable('scan returned 200 with an uninterpretable body; failing closed')
end

record_scan('allow', nil, string.match(body, '"scan_id"%s*:%s*"([^"]*)"'))
