#!/usr/bin/env python3
"""Generate the request-callout config from the hook files.

The three Lua hooks live in plugin/request-callout/hooks/*.lua rather than as
single-line strings inside the JSON, so they are reviewable in a diff and
testable on their own. That matters most for this flavor: it is the one a
Konnect Serverless customer gets, and it is the one with no Kong schema to
validate it.

They are driven by
spec/j_request_callout_spec.lua, and are inlined here. Edit the .lua files;
this rewrites the JSON. A spec fails if the two ever drift.
"""
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "plugin/request-callout/request-callout-prisma-airs-config.json"
HOOKS = ROOT / "plugin/request-callout/hooks"

# The regional hosts, so an EU or APAC tenant picks a name instead of
# transcribing a hostname. This flavor has no schema, so "region" is a build
# choice like every other option here.
REGIONS = {
    "us": "https://service.api.aisecurity.paloaltonetworks.com/v1/scan/sync/request",
    "eu": "https://service-de.api.aisecurity.paloaltonetworks.com/v1/scan/sync/request",
    "apac": "https://service-sg.api.aisecurity.paloaltonetworks.com/v1/scan/sync/request",
}

# A version for the generated artifact. The rockspec header complains
# that the audited plugin had "no version pin, no rollback, no checksum"; this
# flavor ships no rock at all, so the config carries its own version and a digest
# of the hooks it was generated from. A change-advisory board can reference it
# and an operator can tell two deployed configs apart.
VERSION = "0.4.0"

# The single source of truth for the hooks' build-time options. There
# is no Kong schema in a Konnect serverless flavor, so the fail-open/fail-closed
# choice the audit asks for is made here. Change it here; the generator rewrites
# the block in every hook that reads it, and a spec fails if they drift.
OPTIONS = {
    "on_api_error": "block",      # "block" | "allow"
    "app_name": "kong-airs",
    "region": "us",
}

OPTIONS_START = "-- >>> BUILD OPTIONS"
OPTIONS_END = "-- <<< END BUILD OPTIONS"


def _render_options():
    lines = [
        OPTIONS_START + " -- generated by scripts/build_request_callout.py. Edit the",
        "-- OPTIONS dict there, not here: the generator rewrites this block in every hook",
        "-- and spec/j_request_callout_spec.lua fails if the three ever disagree.",
        "--",
        "-- A Konnect Serverless flavor has no Kong schema, so the fail-open /",
        "-- fail-closed choice is a build-time decision rather than a runtime one.",
        "-- It defaults closed, and every exit below reads it rather than",
        "-- hard-coding the answer.",
        "local OPTIONS = {",
    ]
    for key in ("on_api_error", "app_name"):
        lines.append(f"    {key} = '{OPTIONS[key]}',")
    lines += ["}", OPTIONS_END]
    return "\n".join(lines)


def hook(name):
    """The hook source, with its BUILD OPTIONS block regenerated in place.

    Rewritten on disk as well as inlined, so the .lua files stay the runtime
    artifact the spec drives and `git diff` shows the option change.
    """
    path = HOOKS / f"{name}_before.lua"
    text = path.read_text()
    if OPTIONS_START in text:
        start = text.index(OPTIONS_START)
        end = text.index(OPTIONS_END) + len(OPTIONS_END)
        rebuilt = text[:start] + _render_options() + text[end:]
        if rebuilt != text:
            path.write_text(rebuilt)
        text = rebuilt
    return text


def main():
    hooks = {name: hook(name) for name in ("request", "response", "upstream")}
    digest = hashlib.sha256(
        "".join(hooks[name] for name in ("request", "response", "upstream")).encode()
    ).hexdigest()

    config = {
        "name": "request-callout",
        # Version + digest of the hooks this config was generated
        # from. Not read by Kong; it is what makes a deployed config identifiable
        # and a rollback describable.
        "tags": [f"prisma-airs-v{VERSION}", f"hooks-sha256:{digest[:16]}"],
        "service": {"id": "YOUR_SERVICE_ID"},
        "config": {
            "callouts": [
                {
                    "name": "airs_request_scan",
                    "request": {
                        "url": REGIONS[OPTIONS["region"]],
                        "method": "POST",
                        "headers": {
                            "Content-Type": "application/json",
                            "Accept": "application/json",
                            # The token is a vault REFERENCE, so it is
                            # never written into the declarative config or echoed
                            # by a deck dump.
                            # The README once named the wrong variable
                            # here, so Kong could not dereference the vault entry
                            # and sent the literal "{vault://...}" string as the
                            # token -- which AIRS answers 401, which the old
                            # response hook read as "not blocked".
                            "x-pan-token": "{vault://env/prisma-airs-api-key}",
                        },
                    },
                    # Three separate waits, not one
                    # number. The audited plugin hard-coded a single 5 s value
                    # for all three phases; the read timeout is where an AIRS
                    # cold path lands and is the one that needs its own knob.
                    "timeout": {"connect": 2000, "write": 5000, "read": 20000},
                    # `exit` means a transport failure short-circuits rather than
                    # continuing to the upstream. The response hook then decides
                    # what the client sees.
                    "on_error": "exit",
                    "retries": 2,
                }
            ],
            "request": {"before": hooks["request"]},
            "response": {"before": hooks["response"]},
            "upstream": {"before": hooks["upstream"]},
        },
    }

    OUT.write_text(json.dumps(config, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
